### ISSUE TITLE
Got Error during running the code using the example

### ISSUE THREAD

**Issue by YazdanArman** [rienafairefr/pysvgnest#1]
I am trying to run this code, using the API that is given in README.md but I got this error

```
Traceback (most recent call last):
  File "F:\SVG_APP_1\pysvgnest-master\pysvgnest-master\examples\wooden_house\1.py", line 10, in <module>
    nest.nest('combined.svg', files, 600, 300)
TypeError: nest() takes 3 positional arguments but 4 were given
```

and here is my code:
```
from svgnest import nest

files = {
  'chimney.svg': 1,
  'roof.svg': 2
}

nest.nest('combined.svg', files, 600, 300)
```

also I think the given API have a little problem, that is calling the module name instead of calling a function this is why I have used this line
`nest.nest('combined.svg', files, 600, 300)`
instead of
`nest('combined.svg', files, 600, 300)`

**Comment by rienafairefr** [comment]
sorry, haven't run the code in years, like the original author of svgnest in javascript and deepnest (the gui around svgnest)
There is a js branch which might be more up to date/runnable but I have no idea. Haven't need nesting (for laser cutting for me) for years.

**Comment by rienafairefr** [comment]
at some point the nest function was `def nest(files, wbin, hbin)`, the svgnest you have installed is probably after that update.

in that case, nest.nest(files, 600, 300) would probably do the trick, don't remmeber where the output goes though
